### PR TITLE
Check that Xvfb is active after starting it

### PR DESCRIPTION
**Pull request by ghost**
This PR fixes a race condition between Xvfb port binding and tests trying to use the display.

By default (can be disable using a configuration parameter) the plugin will now wait for the port corresponding to the display picked to be opened before proceeding. It will retry N names with a specified timeout. If all the attempts fail the build will fail.

### CODE REVIEW

**Comment by Zetten** [comment]
I'm afraid a couple of the ITs are failing on this one. Both `simple-it` and `args-it` are failing with errors like the below, but the new `activecheck-it` is working. Are the other ITs also working in your environment?

```
[INFO] Setting Maven property 'xvfb.display' to: :25
[INFO] Active check failed, retries remaining: 9
[INFO] Active check failed, retries remaining: 8
[INFO] Active check failed, retries remaining: 7
[INFO] Active check failed, retries remaining: 6
[INFO] Active check failed, retries remaining: 5
[INFO] Active check failed, retries remaining: 4
[INFO] Active check failed, retries remaining: 3
[INFO] Active check failed, retries remaining: 2
[INFO] Active check failed, retries remaining: 1
[INFO] Active check failed, retries remaining: 0
[DEBUG] Unable to start Xvfb by searching for a free port.
org.apache.maven.plugin.MojoExecutionException: Active check failed for display: :25
...
```

**Comment by ghost** [comment]
Sorry about that. I've flipped the default value for checkActive before pushing and didn't notice the test failures.

It think the cause for these test failures is related to the port computation (base + display number. For :99 for example Xvfb is started properly (="export DISPLAY=:99; xeyes" works) but not listening on the expected port (6000 + 99).

I've updated the commit to have XvfbRunMojo.isDisplayActive() attempt to start a client app (xset) on the given display instead. WDYT?

**Comment by Zetten** [comment]
That looks great. It's definitely a more appropriate way to check that the display is active than the simple port check.

I'll merge this and see if I can remember how to do a release...

**Comment by ghost** [comment]
That would be great!

For some reason though it says "Zetten merged 1 commit into Zetten:development from isavin:check_xvfb_active an hour ago" I don't see the commit on development or master in your repository.

**Comment by Zetten** [comment]
Yep, sorry about that. Messed up a rebase 😞

I've just deployed v1.3.0 and it should be in Central fairly soon.

**Pull request merged**
